### ISSUE TITLE
Do not allow panes to be resized so far that the resizing control vanishes

### ISSUE THREAD

**Issue by gvwilson** [tidyblocks/briq#30]
1.  If the horizontal divider in the right pane is pulled up or down too far, it disappears and cannot be regrabbed, so ensure a minimum height for each pane.

2.  Ditto for the vertical divider.

**Comment by DarkMetroid** [comment]
This is currently handled in most cases, but I'm noticing that only for the vertical divider, and only when dragging to the right there's an issue. I stops appropriately before the end, but if you just keep pulling it, it'll snap passed that.

Maybe some kind of manual check of the position on release and a manual repositioning just for this one case.
