### ISSUE TITLE
React Blockly Console errors

### ISSUE THREAD

**Issue by DarkMetroid** [tidyblocks/briq#66]
React blockly doesn't handle xml well and throws console errors. Maybe there's a quick pull request that can solve them?

**Comment by DarkMetroid** [comment]
Figured out a cute solution to this. I'm going to try pushing a PR to react-blockly, if they take too long we'll be able to patch it on our end.

Core idea is to take advantage of the 'is' attribute and add is="div" to the XML stuff.

**Comment by MayaGans** [comment]
🤯
