### ISSUE TITLE
Indicating Updates

### ISSUE THREAD

**Issue by DarkMetroid** [tidyblocks/briq#87]
Thinking some kindof indicator on the tabs to show they've been updated (similar to current tidyblocks.tech).

Also wondering about a success/error thing after we run like this https://material-ui.com/components/snackbars/#customized-snackbars (click 'Open Success Snackbar'). It automatically disappears after a few seconds, and should make it clearer whether things ran or not.

**Comment by gvwilson** [comment]
An indicator on the tabs that fades out after a few seconds and/or is reset the next time "run" is hit would be very useful. If you're going to use icons or background colors, please make sure that the console tab has different indicators for:

-   Everything is a log message (no warnings, no errors): green light
-   There are log and warning messages but no errors: yellow light
-   There are errors: red light

**Comment by MayaGans** [comment]
YAAAS was literally just going to open this issue/feature request! 

Also wondering if it's possible to auto-navigate to plot pane if a plot is generated, or to data if the last block is a data manipulation block?

**Comment by DarkMetroid** [comment]
Yeah, I've gotta think there's something we can use to trigger different tabs, will take a look.
